@startmindmap css技能树
* CSS

** 基础
*** 选择器
*** 属性
*** 值
**** 颜色
**** 特殊属性值-inherit、initial、unset
*** 单位
**** 长度
***** 相对单位
*** 引入位置与权重
*** 重绘、重排
**** contain属性

** 布局
*** position
*** 特定布局
****_ 垂直居中
****_ 多列-多列等高、瀑布流
*** 布局模式
**** table
**** flex
**** grid
*** 非平面布局
**** z轴
**** 3D
***** 景深

** 盒模型
*** 展现-display

*** 外部
****_ margin——auto margin、
*** 边框
**** border
**** outline
**** box-shadow
**** 分隔——区域、item竖线
*** 内部
**** 填充
*****_ 颜色——任意颜色赋色技术
*****_ 混合——mix-blend-mode、background-blend-mode
*****_ 滤镜
*****_ mask
*****_ 渐变——直线(linear-gradient)、角向(conic-gradient)
**** 文字
*****_ font-family
*****_ 外观
*****_ 对齐
*****_ 方向
*****_ 换行
*****_ 省略
**** 背景
*** 特殊形状
****_ 圆、三角、多边、复杂组合
****_ clip-path
****_ shape-outside

** 动画
*** 动画内容
*** 动画运行
*** 动画辅助
**** Graphics Layer
*** 典型案例

** 伪元素

** 性能
*** 网络加载
**** 图片
**** 自定义字体
**** @import资源
*** 慎用通配符
*** 复用-尤其是资源引入型
*** 简写

** 扩展、辅助
*** CSS自定义属性
*** 特性检测

** 特殊css
*** 特殊选择器
****_ :root
****_ :empty
****_ :target
****_ ::focus-within
*** 书写技巧
****_ 渐进增强

@endmindmap