@startmindmap gitignore
* gitignore

++ /
+++_ 文件夹的标志 
+++_ 头部或中部的`/`/，会让匹配的文件相对gitignore文件定位
+++_ 尾部的`/`/，使得pattern只匹配文件夹
++ *
+++_ 匹配除`/`/的0个或多个字符
+++_ `**`匹配包括`/`的0个或多个字符
++ ? 
+++_ 匹配除`/`的0个或1个字符

-- !
---_ 排除逻辑
-- [a-z][A-Z]
---_ 符号集
-- #
---_ 注释
@endmindmap