@startuml 适配者模式
skinparam classAttributeIconSize 0

interface Target {
  request()
}
class Adapter implements Target {
  - adaptee
  + request() \n  adaptee.specialRequest
}
class Adaptee {
  + specialRequest()
}

Client -> Target
Adaptee <-- Adapter
@enduml