@startuml 代理
skinparam classAttributeIconSize 0

abstract class Subject {

}
class ConcreteSubject extends Subject {
  + method()
}
class Proxy {
  - subject Subject
  + method()
  + otherMethod()
}

Client -> Proxy
Proxy --> Subject
@enduml