@startuml 合成模式
skinparam classAttributeIconSize 0

interface Component {
  + add(com: Component): void
  + remove(com: Component): void
  + operation(): void
}
class Leaf {
  ' + add(com: Component): void
  ' + remove(com: Component): void

  + operation(): void
}
class Composite {
  - list: Component[]

  + add(com: Component): void
  + remove(com: Component): void
  + getChild(idx: number): Component

  + operation(): void
}
note as N1
  for com in list
    com.operation()  
end note

Component <|.. Leaf
Component <|.. Composite
Component "n" o-- "1" Composite
Composite <-- N1

@enduml