@startuml 桥模式
skinparam classAttributeIconSize 0

abstract class Abstraction {
  - impl: Implementor
  
  # Abstraction()
  operation(): void
}
class ConcreteAbstraction1 extends Abstraction {
  - impl: Implementor
  operation(): void
}
class ConcreteAbstraction2 extends Abstraction {
  - impl: Implementor
  operation(): void
}
interface Implementor {
  + operation(): void
}
class ConcreteImplementor1 implements Implementor {
  + operation(): void
}
class ConcreteImplementor2 implements Implementor {
  + operation(): void
}
note as N1
impl.operation()
end note

N1 .> Abstraction
Abstraction *- Implementor

@enduml