@startuml 简单工厂
skinparam classAttributeIconSize 0

class Factory {
  +{static} createProduct(): Product
}
together {
  interface Product {}
  class ConcreteProduct1 implements Product {}
  class ConcreteProduct2 implements Product {}
}

Factory -> Product
@enduml