@startuml 工厂方法
skinparam classAttributeIconSize 0

together {
  interface Factory {
    +{static} createProduct(): Product
  }
  class ConcreteFactory1 implements Factory {
    +{static} createProduct(): ConcreteProduct1
  }
  class ConcreteFactory2 implements Factory {
    +{static} createProduct(): ConcreteProduct2
  }
}
together {
  interface Product {}
  class ConcreteProduct1 implements Product {}
  class ConcreteProduct2 implements Product {}
}

Product <.. Factory
ConcreteProduct1 <.. ConcreteFactory1
ConcreteProduct2 <.. ConcreteFactory2
@enduml