@startmindmap 编程
+ 编程
++ 编程基础 -> 架构、设计 -> 项目管理

++ 软件设计
+++ 设计应该贯穿于代码活动，“代码即设计”

++ 软件架构
+++ 一系列相关的抽象模式，用于指导大型软件系统各个方面的设计
+++ 一个结构、行为和属性的高级抽象；组件通信
++++ 分类
+++++_ 分层架构
+++++_ 事件驱动架构
+++++_ 微核架构（插件）
+++++_ 微服务架构
+++++_ 云架构
@endmindmap